version: "3"
services:
  malwarescan:
    container_name: malwarescan
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP="malwarescan.wsgi:application"
    ports:
      - 8080:8080
    entrypoint:
      - /bin/bash
